# Issue template chooser. Templates are listed alphanumerically.
# See: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

blank_issues_enabled: true

contact_links:
  - name: GitHub Discussions
    url: https://github.com/hubos-ai/HubOS/discussions
    about: Ask questions, share ideas, or discuss HubOS here.
  - name: View docs
    url: https://github.com/hubos-ai/HubOS#readme
    about: HubOS docs and guides.
