"""Execution plan schemas for coordinator output."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4


def _utcnow() -> datetime:
    """Return timezone-aware UTC datetime."""
    return datetime.now(timezone.utc)


SCHEMA_VERSION = "1.0.0"


class PlanStepType(str, Enum):
    """Types of steps in an execution plan."""

    SEQUENTIAL = "sequential"
    PARALLEL = "parallel"
    CONDITIONAL = "conditional"


@dataclass(frozen=True)
class PlanStep:
    """
    A single step in an ExecutionPlan.

    Represents the Planning Contract as defined in ARCHITECTURE.md.
    """

    step_id: UUID = field(default_factory=uuid4)
    name: str = ""
    step_type: PlanStepType = PlanStepType.SEQUENTIAL
    worker_provider: Optional[str] = None
    input_data: dict = field(default_factory=dict)
    acceptance_criteria: list[str] = field(default_factory=list)
    depends_on: list[UUID] = field(default_factory=list)
    timeout_seconds: int = 300
    retry_count: int = 0
    created_at: datetime = field(default_factory=_utcnow)


@dataclass(frozen=True)
class ExecutionPlan:
    """
    Complete execution plan generated by coordinator.

    Contains ordered/parallel steps and acceptance criteria
    as defined in the Planning Contract.
    """

    schema_version: str = field(default=SCHEMA_VERSION)
    plan_id: UUID = field(default_factory=uuid4)
    task_id: str = ""
    trace_id: str = ""
    session_id: str = ""
    steps: list[PlanStep] = field(default_factory=list)
    acceptance_criteria: list[str] = field(default_factory=list)
    estimated_duration_seconds: Optional[int] = None
    created_at: datetime = field(default_factory=_utcnow)

    def __post_init__(self) -> None:
        """Validate required fields."""
        if not self.task_id:
            raise ValueError("task_id is required")
        if not self.steps:
            raise ValueError("at least one step is required")
